[hekad]
maxprocs = 1

[LoadavgInput]
type = "FilePollingInput"
ticker_interval = 5
file_path = "/proc/loadavg"
decoder = "LoadavgDecoder"

[LoadavgDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_loadavg.lua"

[LoadavgFilter]
type = "SandboxFilter"
message_matcher = "Type == 'stats.loadavg'"
filename = "lua_filters/loadavg.lua"
ticker_interval = 5
preserve_data = true
    [LoadavgFilter.config]
    rows = 1440
    sec_per_row = 60

[LoadavgInfluxDBEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx_line.lua"
    [LoadavgInfluxDBEncoder.config]
    timestamp_precision= "s"

[LoadavgInfluxDBOutput]
type = "HttpOutput"
message_matcher = "Type == 'stats.loadavg'"
address = "http://127.0.0.1:8086/write?db=loadavg&rp=default&precision=s"
username = "root"
password = "root"
encoder = "LoadavgInfluxDBEncoder"

[LogOutput]
message_matcher = "Type == 'stats.loadavg'"
encoder = "LoadavgInfluxDBEncoder"
